spring:
  application:
    name: springboot-quartz-demo
  datasource:
    ##MySQL数据库
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/springboot_quartz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    #username: root
    #password: 172677

    ##postgreSQL数据库
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot_quartz
    username: postgres
    password: 172677

  quartz:
    ##quartz 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            ##MySQL数据库driverDelegateClass
            ##driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            ##postgreSQL数据库driverDelegateClass
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc

  jpa:
    open-in-view: false
    show-sql: false